### ISSUE TITLE
Variable Defination

### ISSUE THREAD

**Issue by emrulhasan-nlp** [almightyGOSU/ANR#5]
hello, I can't find where the following initialized in ModelZoo. 
1. at line 151: fp_uid_userDoc
2. at line 152:  fp_iid_itemDoc
3. at line 180: fp_wid_wordEmbed
4. at line 182: fp_wordEmbed
Can you please explain where those  variables were defined?
Thanks

**Comment by almightyGOSU** [comment]
Hello, these variables are all defined in [FILEPATHS.py](https://github.com/almightyGOSU/ANR/blob/994562a4ba93ea22eabf1c7c1e3cdfd56c9f7c6a/FILEPATHS.py).

_**ModelZoo**_ imports everything from _utilities.py_, and _utilities.py_ imports everything from _FILEPATHS.py_.

**Comment by almightyGOSU** [comment]
https://github.com/almightyGOSU/ANR/blob/994562a4ba93ea22eabf1c7c1e3cdfd56c9f7c6a/FILEPATHS.py#L12-L15

**Comment by emrulhasan-nlp** [comment]
Hello,
Thank you very much!
